# Generated by Django 3.0.1 on 2019-12-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Название места')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка на google maps')),
                ('text', models.TextField(verbose_name='Описание места')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение места')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
