# Generated by Django 3.0.1 on 2019-12-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='text',
            field=models.TextField(max_length=450, verbose_name='Описание места'),
        ),
    ]
