# Generated by Django 3.0.1 on 2019-12-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191226_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='text',
            field=models.TextField(help_text='Максимальная длина: 450 символов', max_length=450, verbose_name='Описание места'),
        ),
    ]
