# Generated by Django 3.0.1 on 2019-12-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20191220_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
